### ISSUE TITLE
Extract public key from private key later?

### ISSUE THREAD

**Issue by getify** [harveyconnor/curve25519-js#2]
I know the `generateKeyPair()` function in this lib returns both private-key and public-key. However, if I persist only the private key, and then later need to get back the public-key, can that be done with any of the code from this library?

**Comment by harveyconnor** [comment]
No, this only generates a Keypair based on a seed.

**Comment by getify** [comment]
Would you accept a PR adding that capability to this library? That logic exists and works quite well in the tweetnacl library (public domain code), but unfortunately, their signing uses Ed25519 curves (64 bytes), while ECDH is Curve25519 curves (32 bytes) for ECDH. So they make them incompatible and force you to use two keypairs, which I dislike.

I'd rather not use both libs, and just use this one if it had the public-key computation from an existing private key.

**Comment by harveyconnor** [comment]
Probably best if you just do a patch package, it's unlikely that I'll maintain this package any further. Or fork and publish your own.
